### ISSUE TITLE
Proposed features

### ISSUE THREAD

**Issue by AnthonyByansi** [rashidkisejjere0784/Lingo-Chat#2]
@rashidkisejjere0784 
Here are the proposed features we can work. We can have them distributed amongst contributors. 
![image](https://github.com/user-attachments/assets/0fdf6570-2646-4471-843a-6ebbf26669b1)

**Comment by rashidkisejjere0784** [comment]
Sure thing, though almost all the features there are already implemented unless you suggest a redo of the project
